version: '3'
services:
    app:
        image: webspace-ng
        build: ./build
        restart: always
        environment:
            - FLASK_ENV=${FLASK_ENV}
        volumes:
            - ./app:/opt/app:ro
            - /var/lib/lxd/unix.socket:/var/lib/lxd.socket
        ports:
            - 8080:8080
